version: '3.8'
services:
  # -----------------------------------
  # PostgreSQL for Scrapper Microservice
  # -----------------------------------
  scrapper-db:
    container_name: scrapper-db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres_scrapper
      POSTGRES_PASSWORD: postgres_scrapper_pass
      POSTGRES_DB: scrapper_db
    ports:
      - "5433:5432"
    volumes:
      - scrapper_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_scrapper -d scrapper_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
  sentiment-hf:
    build: ./sentiment-hf
    container_name: sentiment-hf
    networks: [backend]
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:8000/sentiment",
             "-H", "Content-Type: application/json",
             "-d", "{\"text\":\"ok\"}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ------------------------
  # Zookeeper for Kafka
  # ------------------------
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.9.0.arm64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend

  # ------------------------
  # Kafka Broker
  # ------------------------
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.9.0.arm64
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend

volumes:
  scrapper_db_data:

networks:
  backend:
    driver: bridge
