server:
  port: 8080
spring:
  application:
    name: x-scrapper
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  dataSource:
    url: jdbc:postgresql://localhost:5433/scrapper_db
    driverClassName: org.postgresql.Driver
    username: postgres_scrapper
    password: postgres_scrapper_pass
  jpa:
    hibernate:
      dialect: org.postgresql.Driver
      ddlAuto: update
    showSql: false
  properties:
    hibernate:
      format_sql: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect

proxy-seller:
  username: &proxy-username dummy-proxy-username
  password: &proxy-password dummy-proxy-password
  port: &proxy-port 1234

x:
  credentials:
    -
      username: dummyUsername1
      email: dummyEmail1@gmail.com
      password: dummyPass1
      cookie-path: "cookies1.json"
      proxy:
        host: ""
        port: ""
        username: ""
        password: ""
      use-proxy: false
    -
      username: dummyUsername2
      email: dummyEmail2@gmail.com
      password: dummyPass2
      cookie-path: "cookies2.json"
      use-proxy: true
      proxy:
        host: 123.123.123.123
        port: *proxy-port
        username: *proxy-username
        password: *proxy-password

gologin:
  token: "twój_token_API_z_GoLogin"  # Uzyskaj z https://app.gologin.com/personalArea/TokenApi
  profiles:
    USER_2: "twoje_ID_profilu_2"    # ID profilu (nie nazwa)
    USER_3: "twoje_ID_profilu_3"    # ID profilu widoczne w URL
    USER_4: "twoje_ID_profilu_4"    # np. https://app.gologin.com/profile/62c4fb1c2c61be2d32c53683