server:
  port: 8080
spring:
  application:
    name: x-scrapper
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  dataSource:
    url: jdbc:postgresql://localhost:5433/scrapper
    driverClassName: org.postgresql.Driver
    username: postgres_scrapper
    password: postgres_scrapper_pass
  jpa:
    hibernate:
      dialect: org.postgresql.Driver
      ddlAuto: update
    showSql: false
  properties:
    hibernate:
      format_sql: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect

x:
  username: dummy
  email: dummy@gmail.com
  password: dummy